### PR TITLE
Cube demo replace use of VK_MVK_macos_surface & VK_MVK_ios_surface extensions with VK_EXT_metal_surface extension.

### PR DESCRIPTION
**Pull request by billhollings**
MoltenVK now supports the VK_EXT_metal_surface extension. This PR modifies the cube demo to use that extension to create the surface, instead of the obsolete VK_MVK_macos_surface & VK_MVK_ios_surface extensions.

### CODE REVIEW

**Comment by billhollings** [comment]
Per the request on my related [VulkanSamples](https://github.com/LunarG/VulkanSamples/pull/250#issuecomment-509393764) PR, I've squashed the commits here into one.

**Comment by billhollings** [comment]
Ping. Can I get this merged so that I can update MoltenVK to use it?

**Comment by jeremyk-lunarg** [comment]
Getting the following error when building on my Mac Laptop:

```
[ 24%] Linking C executable vkcube.app/Contents/MacOS/vkcube
Undefined symbols for architecture x86_64:
  "_demo_main", referenced from:
      -[DemoViewController viewDidLoad] in DemoViewController.m.o
  "_demo_run", referenced from:
      _DisplayLinkCallback in DemoViewController.m.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [cube/vkcube.app/Contents/MacOS/vkcube] Error 1
make[1]: *** [cube/CMakeFiles/vkcube.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by billhollings** [comment]
@jeremy-lunarg 

What version of MoltenVK are you using? 

There is a coordination component here...in that the cube demo is being modified to use a different surface extension...which is only supported in MoltenVK repository as of July 3. The MoltenVK in the last SDK won't work.

**Comment by jeremyk-lunarg** [comment]
@billhollings 
Tried with `master` and `aa6a10570a4ce0077120d49dd24c70fd5f5d8481`.

Getting the following error during build still:

```
[ 24%] Linking C executable vkcube.app/Contents/MacOS/vkcube
Undefined symbols for architecture x86_64:
  "_vkCreateMetalSurfaceEXT", referenced from:
      _demo_init_vk_swapchain in DemoViewController.m.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [cube/vkcube.app/Contents/MacOS/vkcube] Error 1
make[1]: *** [cube/CMakeFiles/vkcube.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jeremyk-lunarg** [comment]
Might be best if you update the known_good.json with the MoltenVK commit that works for you and add that change to this PR as well.

**Comment by billhollings** [comment]
@jeremy-lunarg 

The MoltenVK commit that you specified compiles against MoltenVK in the MoltenVK cube demo, which builds against MoltenVK directly.

Does the build process in Vulkan-Tools build against MoltenVK directly, or the Loader? And does the Loader support `vkCreateMetalSurfaceEXT()` from the `VK_EXT_metal_surface` extension?

**Comment by jeremyk-lunarg** [comment]
Vulkan-Tools builds against the Loader.

@lenny-lunarg, you would probably be able to answer @billhollings question better than I could.

**Comment by lenny-lunarg** [comment]
The loader does not currently support the `VK_EXT_metal_surface` extension. Furthermore, surfaces are a little bit of a special case within the loader.

I can add loader support for this extension, but I probably can't get around to that until the end of the week. On top of that, you may need to make changes to moltenvk to make them work together nicely. A driver needs to implement version 3 of the interface for the loader to allow it to implement the create surface functions.

Of course, since I don't have easy access to a machine running macOS, I might need some help to get this loader change up and running.

**Comment by billhollings** [comment]
Thanks, @lenny-lunarg .

As I understand the Loader versioning, MoltenVK already supports version 5:

```
MVK_PUBLIC_SYMBOL VkResult vk_icdNegotiateLoaderICDInterfaceVersion(
	uint32_t*                                   pSupportedVersion) {

	MVKTraceVulkanCallStart();

	// This ICD expects to be loaded by a loader of at least version 5.
	VkResult rslt = VK_SUCCESS;
	if (pSupportedVersion && *pSupportedVersion >= 5) {
		*pSupportedVersion = 5;
	} else {
		rslt = VK_ERROR_INCOMPATIBLE_DRIVER;
	}
	MVKTraceVulkanCallEnd();
	return rslt;
}
```

...and it certainly has always supported the other surface extensions: `VK_MVK_macos_surface` & `VK_MVK_ios_surface`.

But let me know if there is anything else we can add to MoltenVK to help with this.

And I'm happy to help with testing on macOS if you need.

**Comment by billhollings** [comment]
Just a note....

On macOS, the Cube demo should be run with the `--use_staging` CLI argument, because macOS does not support backing textures with host-coherent memory.

**Comment by jeremyk-lunarg** [comment]
Because this PR is so far behind, I cherry-picked the commit onto a new branch and created a new PR.

Please refer to PR #297 for future discussion on this change.
Closing.

**Pull request closed without merging**
