### PR TITLE
build: Fix android update not understanding headers version

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by jeremyk-lunarg** [comment]
There doesn't seem to be any changes in this PR.
What is this PR supposed to do?

**Comment by krOoze** [comment]
Removes endline

Script complained that revision `v1.1.130?` does not exist

**Comment by krOoze** [comment]
Should show now.

**Comment by jeremyk-lunarg** [comment]
Seems that this file has been updated since our last header update.
Could you check if the header update fixed this problem?

**Comment by krOoze** [comment]
The actual underlying problem seems to be that your `.gitattributes` overrides my `core.autocrlf=false`, so I get CRLF in the file.

Anyway, probably the newline here serves no purpose, and rest of the repo seemed to compile fine last time. So I am gonna rebase this.

**Comment by jeremyk-lunarg** [comment]
What script was complaining that it couldn't find the appropriate headers tag for Android?

**Comment by krOoze** [comment]
Simply the `./update_external_sources_android.sh --no-build` trying to checkout the headers:

> Creating local Vulkan-Headers repository (/mnt/c/Dev/_GitHub/Vulkan-Tools/build-android/third_party/Vulkan-Headers).
Cloning into '.'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 1297 (delta 14), reused 9 (delta 2), pack-reused 1261
Receiving objects: 100% (1297/1297), 5.76 MiB | 2.63 MiB/s, done.
Resolving deltas: 100% (695/695), done.
error: pathspec 'v1.2.132?' did not match any file(s) known to git.

This is on the Ubuntu subsystem on Windows. I believe direct Windows path is currently defunct (#320).

**Pull request merged**
