### PR TITLE
repo: Update the clang style from VVL

### PR DESCRIPTION
**Pull request by krOoze**

### CODE REVIEW

**Comment by jeremyk-lunarg** [comment]
What motivated this PR?

**Comment by krOoze** [comment]
just me noticing the class access specifiers are misaligned when doing some custom work.

**Comment by mikew-lunarg** [comment]
@jeremyk-lunarg 
.clang-format is in all the Vulkan repos, and I recommend it be kept identical across all those repos.

As @krOoze mentions, it was changed in VVL in Sep 2019, so that single instances is now different.

**Comment by jeremyk-lunarg** [comment]
Alright. Merging.

**Comment by mikew-lunarg** [comment]
So @krOoze as you're driving this initiative, could you ensure this change goes in to all the repos, so the .clang-format remains identical:
1. KhronosGroup/Vulkan-Loader
2. KhronosGroup/Vulkan-ValidationLayers
3. KhronosGroup/Vulkan-Tools
4. LunarG/VulkanSamples
5. LunarG/VulkanTools

**Comment by krOoze** [comment]
@mikew-lunarg Ups, I got accidentally promoted to initiative leader... :D

**Comment by mikew-lunarg** [comment]
@krOoze that'll learn ya ;-)

**Pull request merged**
