### PR TITLE
Update linmath to upstream.

### PR DESCRIPTION
**Pull request by dwolowb**
This fixes bug in linmath.h unused function: quat_mul_vec3
Linmath is taken from upstream: [https://github.com/datenwolf/linmath.h](https://github.com/datenwolf/linmath.h)
Added function definition: degreestoradians

### CODE REVIEW

**Review by charles-lunarg — APPROVED** [review]
Awesome, this is great to have. Thanks for updating it!

**Comment by charles-lunarg** [comment]
Oh right, due to policy you'll have to sign the CLA. Should be as simple as clicking the link and agreeing to it.

**Comment by dwolowb** [comment]
Hi, this pull request is now passing all checks. There was a warning on windows about float/double conversion that has been fixed with explicit float casts.
As a recap, then changes made: 

- Update linmath.h from upstream.
- Add degreestoradians function.
- Cast doubles as floats in unused function: mat4x4_arcball

As a note the linmath.h added in this PR does not contain the copyright at the top of the file.

**Comment by charles-lunarg** [comment]
Because linmath.h isn't from this repo, I'm not sure whether it should have a copyright for people who didn't write it. 

Thank you for going ahead and fixing the compiler issues. I'll go ahead and merge it in :)

**Pull request merged**
