### PR TITLE
repo: Layer json version automation

### PR DESCRIPTION
**Pull request by joey-lunarg**
Change-Id: I0f71808bf58997e58599b3cb00bb23b8dd179f3c

### CODE REVIEW

**Comment by mikew-lunarg** [comment]
Are the changes to this FindVulkanHeaders.cmake made by copying over that file from another Khr repo?

If so, it would be good to identify that in this PR's comments (which repo, and at what commitID)

If not, what is the reason for deviation?  I would hope all instances of that .cmake file are identical across repos.

**Comment by joey-lunarg** [comment]
These changes are copied over from Vulkan-Loader, so we already have an inconsistency. I can make the effort to make them consistent across the repos.

**Comment by jeremyk-lunarg** [comment]
@shannon-lunarg @mikew-lunarg Is this still relevant?

**Comment by mikew-lunarg** [comment]
Shannon did give thumbs up way back when, but it wasn't merged.
Don't know whether it's still appropriate for the current state of the tree.

**Comment by jeremyk-lunarg** [comment]
Closing for now since there are merge conflicts and the tree has moved forward.

If we want something like this in the future, we can either reopen with fixes or open a new PR with necessary changes.

**Pull request closed without merging**
