### PR TITLE
build: Update to header 1.3.281

### PR DESCRIPTION
**Pull request by mikes-lunarg**

### CODE REVIEW

**Review by charles-lunarg — APPROVED** [review]
The code changes appear fine, but the CI check failing makes it seem like not all files which should have been changed were.

**Comment by mikes-lunarg** [comment]
> The code changes appear fine, but the CI check failing makes it seem like not all files which should have been changed were.

I'm trying a new method of updating the branches this week. Looks like it missed the MockICD json file.  Also a Vulkan-Hpp issue on windows? Not sure what is going on there yet

**Comment by mikes-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-Hpp/issues/1833

**Comment by mikes-lunarg** [comment]
Closing this because of the Vulkan-Hpp issue in 281. Issue has been fixed upstream so we will pick it up when 282 is released.

**Pull request closed without merging**
