### PR TITLE
Add public support for QNX to vulkaninfo

### PR DESCRIPTION
**Pull request by mgorchak-blackberry**
Add public support for QNX to vulkaninfo

Sample output:
`
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.261

Instance Extensions: count = 16
===============================
        VK_EXT_debug_report                    : extension revision 10
        VK_EXT_debug_utils                     : extension revision 2
        VK_EXT_direct_mode_display             : extension revision 1
        VK_EXT_display_surface_counter         : extension revision 1
        VK_KHR_device_group_creation           : extension revision 1
        VK_KHR_display                         : extension revision 23
        VK_KHR_external_fence_capabilities     : extension revision 1
        VK_KHR_external_memory_capabilities    : extension revision 1
        VK_KHR_external_semaphore_capabilities : extension revision 1
        VK_KHR_get_display_properties2         : extension revision 1
        VK_KHR_get_physical_device_properties2 : extension revision 2
        VK_KHR_get_surface_capabilities2       : extension revision 1
        VK_KHR_portability_enumeration         : extension revision 1
        VK_KHR_surface                         : extension revision 25
        VK_LUNARG_direct_driver_loading        : extension revision 1
        VK_QNX_screen_surface                  : extension revision 1

Layers: count = 1
=================
VK_LAYER_KHRONOS_validation (Khronos Validation Layer) Vulkan version 1.2.190, layer version 1:
        Layer Extensions: count = 3
                VK_EXT_debug_report        : extension revision 9
                VK_EXT_debug_utils         : extension revision 1
                VK_EXT_validation_features : extension revision 2
        Devices: count = 1
                GPU id = 0 (Samsung Xclipse 930A)
                Layer-Device Extensions: count = 3
                        VK_EXT_debug_marker     : extension revision 4
                        VK_EXT_tooling_info     : extension revision 1
                        VK_EXT_validation_cache : extension revision 1

Presentable Surfaces:
=====================
GPU id : 0 (Samsung Xclipse 930A):
        Surface type = VK_QNX_screen_surface
        Formats: count = 8
                SurfaceFormat[0]:
                        format = FORMAT_B8G8R8A8_UNORM
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[1]:
                        format = FORMAT_B8G8R8A8_SRGB
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[2]:
                        format = FORMAT_R8G8B8A8_UNORM
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[3]:
                        format = FORMAT_R8G8B8A8_SRGB
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[4]:
                        format = FORMAT_A2R10G10B10_UNORM_PACK32
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[5]:
                        format = FORMAT_A2B10G10R10_UNORM_PACK32
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[6]:
                        format = FORMAT_A1R5G5B5_UNORM_PACK16
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
                SurfaceFormat[7]:
                        format = FORMAT_R5G6B5_UNORM_PACK16
                        colorSpace = COLOR_SPACE_SRGB_NONLINEAR_KHR
        Present Modes: count = 4
                PRESENT_MODE_IMMEDIATE_KHR
                PRESENT_MODE_MAILBOX_KHR
                PRESENT_MODE_FIFO_KHR
                PRESENT_MODE_FIFO_RELAXED_KHR
...
...
...
`

### CODE REVIEW

**Comment by charles-lunarg** [comment]
To add autogen support you’ll need to modify the python script to allow qnx extensions to be generated

**Comment by mgorchak-blackberry** [comment]
> To add autogen support you’ll need to modify the python script to allow qnx extensions to be generated

Do you mean some particular script? I added VK_USE_PLATFORM_SCREEN_QNX a long time ago to most scripts. The only unmodified one is vulkan_wrapper, but as far as I can see it is only for Android.

**Comment by charles-lunarg** [comment]
I mean the scripts/vulkaninfo_generator. It’ll generate code for various pNext chains, but currently only generates for KHR and EXT extensions.

**Comment by mgorchak-blackberry** [comment]
> 

Under QNX we have two extensions VK_QNX_screen_surface, and I don't see any other surface extensions handled by vulkaninfo, all of them are manually initialized per platform in the vulkainfo.h, which seems like a not generated file.

And VK_QNX_external_memory_screen_buffer - buffer import extension which also not a subject of vulkaninfo reporting due to tight bounds to the QNX's composition manager. I don't see any other buffer import extensions like DMABUF handled by vulkaninfo.

So I think we're fine with everything we have currently.

Thank you!

**Review by charles-lunarg — APPROVED** [review]

**Pull request merged**
