### PR TITLE
cube: remove unnecessary use-xlib

### PR DESCRIPTION
**Pull request by poweif**

### CODE REVIEW

**Comment by poweif** [comment]
> While the code change looks appropriate, I will mention that the same changes are applicable to vkcube.cpp. It would be stellar if you could tackle that as well, but that isn't something you have to do to get this change merged (just passing CI is enough)

Hi, I'm not aware of vkcube.cpp and I couldn't find it in the repo. I'd happy to take a look if you could point me to the file.  Thanks!

**Comment by poweif** [comment]
I don't have write access. Can someone with write access please merge?  Thank you!

**Comment by juan-lunarg** [comment]
> I can merge it, but I would like it to be clear if you were going to modify cube.cpp as well. I try to keep them in sync, hence me asking.

Do you mean cube.c?

**Comment by charles-lunarg** [comment]
Wait, the changes were originally to cube.c. Now they are to cube.cpp. I was asking for *both* files to be changed.

**Comment by charles-lunarg** [comment]
I think I am just going crazy is all.

It appears that this PR has always been modifying cube.cpp. I thought it was modifying cube.c, so when I looked at cube.cpp, I saw the 'same' thing that this PR was removing, and so thought the changes were needed in both files. 

So yeah, this PR is fine and I was just mistaken the entire time.

**Pull request merged**
