### PR TITLE
Bump mock icd surface caps

### PR DESCRIPTION
**Pull request by null77**
@tobine @mark-lunarg PTAL. Had to update the known-good in the process.

### CODE REVIEW

**Comment by null77** [comment]
Fixes #436

**Comment by shannon-lunarg** [comment]
I'm driving to get the validation layers known-good up to 151 by the end of the day. Vulkan-Tools 151 known-good update will follow shortly after that. I'm letting you know where I'm at with the update because the v1.2.150 tag in Vulkan-Loader is actually not the ideal tag for this update (there were some fixes added after the repo was tagged). `3cdfc04bc447c7e4d4faeb18821f3f59c77a6cca ` would be the ideal commit for the 150 update.

**Comment by null77** [comment]
NP, just let me know when/if you need action from me to land this CL.

**Comment by shannon-lunarg** [comment]
@null77 I've updated the known-good to 1.2.151 (in #438). I hope that unblocks you!

**Comment by null77** [comment]
@shannon-lunarg PTAL, I rebased on master and dropped my known-good update in favor of yours.

**Comment by jeremyk-lunarg** [comment]
Passed internal CI tests.
Merging.

**Comment by null77** [comment]
Thanks!

**Pull request merged**
