### PR TITLE
vulkaninfo: Add quotes around NULL

### PR DESCRIPTION
**Pull request by charles-lunarg**
Used PrintKeyValue instead of PrintKeyString by mistake.

### CODE REVIEW

**Review by jeremy-lunarg — APPROVED** [review]
Tested locally. Works. Thanks @charles-lunarg!

**Review by lunarpapillo — COMMENTED** [review]
Why was this not found before?  Generator issues are typically found early.

Why did the repository tests not catch the issue?  Has a new test case been added that can detect the failure?

**Comment by richard-lunarg** [comment]
@lunarpapillo These kind of failures show up from time to time, they are always specific to the hardware in use by the manual tester.

**Comment by charles-lunarg** [comment]
> Why was this not found before? Generator issues are typically found early.
> 
> Why did the repository tests not catch the issue? Has a new test case been added that can detect the failure?

This specific issue is really due to PrintKeyValue not being 'protected' against printing strings, which is easy to do by mistake. 

So yes, it is annoying that it was only found due to testing on a specific platform, but is something that could have been prevented (at the compile stage, let alone the test stage)

**Pull request merged**
