### PR TITLE
build: Update known-good files for 1.2.162 header

### PR DESCRIPTION
**Pull request by shannon-lunarg**
Changes:
- Updated `known_good.json`
- Generated new source files

Running through internal CI

### CODE REVIEW

**Review by jeremyk-lunarg — APPROVED** [review]
Builds on macOS.

**Comment by shannon-lunarg** [comment]
Passes internal CI 

Do the changes in `b4ef19a` seem reasonable? @jeremyk-lunarg

**Comment by jeremyk-lunarg** [comment]
> Passes internal CI
> 
> Do the changes in `b4ef19a` seem reasonable? @jeremyk-lunarg

A quick search of the spec does not show any reference to `vkBindAccelerationStructureMemoryKHR`.

If it's not in the spec for this header, it makes sense to remove it to me.

**Comment by shannon-lunarg** [comment]
@jeremyk-lunarg I made a much larger change in the second commit than was there previously. @Tony-LunarG pointed out, the proper way to update `vulkan_wrapper.cpp` is by updating `generate_vulkan_wrapper.py` so I went through the process found here: https://github.com/KhronosGroup/Vulkan-Tools/tree/master/common 
I think it would be a good idea to test again on mac. Hopefully this Just Works (TM).

**Comment by shannon-lunarg** [comment]
Passed internal CI again.

**Review by jeremyk-lunarg — APPROVED** [review]
Builds on macOS.

**Comment by shannon-lunarg** [comment]
All changes pushed to master.

**Pull request closed without merging**
