### PR TITLE
vulkaninfo: Add VK_EXT_pci_bus_info

### PR DESCRIPTION
**Pull request by jeremyk-lunarg**
Added VK_EXT_pci_bus_info extension to Vulkan Info.
Print data from struct
VkPhysicalDevicePCIBusInfoPropertiesEXT.

### CODE REVIEW

**Comment by jeremyk-lunarg** [comment]
It seems like at least some of the structs filled by VkGetPhysicalDeviceProperties and VkGetPhysicalDeviceFeatures could be code generated.  For now I'm trying to catch up on work that needs to be done on vulkaninfo and once I get some breathing room I'll try to start building code generation.

**Comment by arunsivaramanneo** [comment]
is there any dependency to see this fields in vulkaninfo... last few commits are not showing any changes in linux vulkaninfo ...I can see the EXT_PCI_Info extensions but not displayed in Properties, even the Float_Control i can see the extension but no properties and also the new formats that got added recently. appreciate if anyone can update here if it works fine on Linux

**Comment by jeremyk-lunarg** [comment]
It seems to be working fine on my personal Linux system and our CI system here.
What version of the repos are you using?
Are you using the known good repos for Vulkan-Tools?
Are you using the SDK and if so, are you using the Linux packages or the tar ball?

**Comment by mikes-lunarg** [comment]
I am able to run the latest vulkaninfo against the top-of-tree intel mesa driver and see properties for VK_EXT_pci_bus_info with the following caveat: The specification for `VkPhysicalDevicePCIBusInfoPropertiesEXT` changed in an incompatible way in the 1.1.96 header and mesa is already using the new format.  vulkaninfo *must* be compiled with the 96 or newer header when using the latest mesa driver to avoid heap corruption.

**Comment by arunsivaramanneo** [comment]
> It seems to be working fine on my personal Linux system and our CI system here.
> What version of the repos are you using?
> Are you using the known good repos for Vulkan-Tools?
> Are you using the SDK and if so, are you using the Linux packages or the tar ball?

@jeremy-lunarg I have cloned Vulkan tools and have installed as per the Build.md instruction with Vulkan loader and Headers. I am using nvidia's driver 415.18.04 and also Mesa Intel driver 18.99 from Padoka PPA and still don't see the last few commits. Attaching the file

[vulkaninfo.txt](https://github.com/KhronosGroup/Vulkan-Tools/files/2693101/vulkaninfo.txt)

**Comment by jeremyk-lunarg** [comment]
@arunsivaramanneo Could you run `git log` in your Vulkan-Tools directory and send me the commit ID of HEAD?

**Comment by arunsivaramanneo** [comment]
@jeremy-lunarg please find the log attached
[log.txt](https://github.com/KhronosGroup/Vulkan-Tools/files/2696097/log.txt)

**Comment by arunsivaramanneo** [comment]
Thanks had to rebuild from scratch .. it works now .. thanks

**Comment by jeremyk-lunarg** [comment]
You're welcome.  Glad I could help.

**Pull request merged**
