### PR TITLE
build: Update to header 1.2.202

### PR DESCRIPTION
**Pull request by mikes-lunarg**
- Update known-good
- Generate source (no change)

### CODE REVIEW

**Review by charles-lunarg — APPROVED** [review]
No function pointers here? 
Does MockICD not intercept all functions? or maybe I just misunderstood how its autogen works.

**Comment by mikes-lunarg** [comment]
Filed https://github.com/KhronosGroup/Vulkan-Hpp/issues/1161 for the cube.cpp CI errors

**Comment by charles-lunarg** [comment]
Is this fixed upstream and should we retry the PR?

**Comment by mikes-lunarg** [comment]
> Is this fixed upstream and should we retry the PR?

It is fixed upstream in Vulkan-Hpp, but we won't be able to use it until Vulkan-Headers picks it up in next release

**Comment by mikes-lunarg** [comment]
Closing in favor of #604

**Pull request closed without merging**
