### PR TITLE
cube: Use time-based animation

### PR DESCRIPTION
**Pull request by joey-lunarg**
Update the cube's angle based on the elapsed time and angle-per-second,
instead of a fixed angle per frame.

Change-Id: Iffe33098203c27045798e85277a04c5f28de7da9

### CODE REVIEW

**Comment by karl-lunarg** [comment]
`cubepp` seems to run OK, but for me, `cube` rotates really slowly, like about less than 1 degree/sec.  (Ubuntu 16.04)

**Comment by karl-lunarg** [comment]
`cube` looking better now.  I still need to review code.

**Comment by jeremyk-lunarg** [comment]
@karl-lunarg @dustin-lunarg Does this still look good?  Can we merge this or does it still need changes?

**Comment by jeremyk-lunarg** [comment]
Determined to add unwanted complexity.
Closing issue.

**Pull request closed without merging**
